# Generated by Django 3.1.5 on 2021-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_contestquestions_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(upload_to='memes/'),
        ),
    ]
