# Generated by Django 3.1.5 on 2021-06-21 01:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210530_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowships',
            name='url',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='internships',
            name='url',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='scholorships',
            name='url',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
