# Generated by Django 3.1.5 on 2021-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210621_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AlterField(
            model_name='contestquestions',
            name='img',
            field=models.ImageField(upload_to='cq/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='coursesforinterviews',
            name='image',
            field=models.ImageField(upload_to='ci/'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='image',
            field=models.ImageField(upload_to='gifts/'),
        ),
    ]
