# Generated by Django 3.1.5 on 2021-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210622_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='KLCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ckl/')),
                ('content', models.TextField(default='Content to be displayed')),
            ],
        ),
    ]
