# Generated by Django 3.1.5 on 2021-06-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_klcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfiles',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.klcourse'),
        ),
    ]
